services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn minicatalog.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: minicatalog.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
